ifluxblog:
  build: iflux-blog
  env_file:
    .env
  ports:
    - "4000:4000"
ifluxsrv:
  build: iflux-server
  environment:
    NODE_ENV: docker
  env_file:
    .env
  ports:
    - "3000:3000"
  links:
    - mongo
ifluxsrvdata:
  build: iflux-server-data
  volumes:
    - "/data/db:/data/db"
ifluxslack:
  build: iflux-slack
  environment:
    NODE_ENV: docker
  env_file:
    .env
  ports:
    - "3001:3000"
ifluxmetrics:
  build: iflux-metrics
  environment:
    NODE_ENV: docker
  env_file:
    .env
  links:
    - mongo
  ports:
    - "3002:3000"
ifluxstarter:
  build: iflux-starter
  links:
    - ifluxsrv
    - ifluxslack
    - ifluxmetrics
citizen:
  build: citizen-engagement
  environment:
    NODE_ENV: docker
  env_file:
    .env
  links:
    - mongo
  ports:
    - "3003:3000"
publibike:
  build: publibike
  environment:
    NODE_ENV: docker
  env_file:
    .env
mongo:
  image: mongo
  ports:
    - "27017:27017"
  volumes_from:
    - ifluxsrvdata

