ifluxapidoc:
  image: softengheigvd/iflux-apidoc:latest
  env_file: ./.env
  ports:
    - "4000:4000"
ifluxsrv:
  image: softengheigvd/iflux-server-node:v0.2.0
  env_file: ./.env
  ports:
    - "3000:3000"
  links:
    - mongo
ifluxsrvdata:
  build: iflux-server-data
  volumes:
    - "/data/db:/data/db"
ifluxslack:
  image: softengheigvd/iflux-slack-gateway:v0.2.0
  env_file: ./.env
  ports:
    - "3001:3000"
ifluxmetrics:
  image: softengheigvd/iflux-metrics-action-target:v0.2.2
  env_file: ./.env
  links:
    - mongo
  ports:
    - "3002:3000"
ifluxmapbox:
  image: softengheigvd/iflux-mapbox-viewer:v0.2.1
  env_file: ./.env
  ports:
    - "3004:3000"
  env_file:
    .env
ifluxstarter:
  image: softengheigvd/iflux-server-starter:v0.0.4
  env_file: ./.env
  links:
    - ifluxsrv
    - ifluxslack
    - ifluxmetrics
    - ifluxmapbox
citizen:
  image: softengheigvd/citizen:v0.2.3
  env_file: ./.env
  links:
    - mongo
  ports:
    - "3003:3000"
publibike:
  image: softengheigvd/iflux-publibike-event-source:v0.1.3
  env_file: ./.env
mongo:
  image: mongo
  command: mongod --smallfiles
  ports:
    - "27017:27017"
  volumes_from:
    - ifluxsrvdata

