ifluxblog:
  build: iflux-blog
  env_file:
    .env
  ports:
    - "4000:4000"
ifluxsrv:
  build: iflux-server
  environment:
    NODE_ENV: docker
  ports:
    - "3000:3000"
  links:
    - mongo
ifluxsrvdata:
  build: iflux-server-data
  volumes:
    - "/data/db:/data/db"
ifluxslack:
  build: iflux-slack
  env_file:
    .env
  ports:
    - "3001:3000"
mongo:
  image: mongo
  ports:
    - "27017:27017"
  volumes_from:
    - ifluxsrvdata

